### ISSUE TITLE
Failure to start when running on multi-monitor setup

### ISSUE THREAD

**Issue by outlander-a** [seb3773/q4osXpack#21]
qxpack bash script fails to start when run on a computer with a multi-monitor set-up (my case: one 1920x1080 screen and one 1280x1024 screen, TDE desktop extended to both screens).

The failure is in the 3rd line of code, where it tries to place the menu window in the centre of the screen:

center_x=$(( ($screenw - $1) / 2 ));center_y=$(( ($screenh - $2) / 2 ));kgeo="${1}x${2}+$center_x+$center_y";echo "$kgeo";}

I assume that the same would happen when running qperf, qtheme and other scripts individually as they all rely on the same code, but I did not test it.

The workaround is to switch to outputting the image to only one monitor for the duration of running the script.

Also, wanted to say a huge "thank you" for making this script! :smiley:

**Comment by seb3773** [comment]
First, thanks for your message, I'm really happy this script is usefull for other people :)
It motivates me to improve it (and to continue the 'not yet finished parts', especially system tools) and correct some other little bugs.

And thanks for your bug issue too, stupid mistake from me, didn't test the new version of the script on a multi monitors installation (I tested previous versions with two monitors, but it was only command line at this time, so this function didn't exist...)

I corrected it (by the way I realized this will be better sourced in a common script than repeated at each individual scripts :p, will optimize it later), it should be ok now :)
