### ISSUE TITLE
request_q4osteam - (low priority) / menu glyph

### ISSUE THREAD

**Issue by seb3773** [seb3773/q4osXpack#7]
How can I change this symbol (used in all menus) ? Can't find what image/icon is involved... Doesn't seem to be font dependant either... Is it hard-coded ?

![menu_glyph](https://github.com/seb3773/Q4OSseb/assets/99963207/19112e1b-0735-498d-8c12-9e14d2fb95de)

**Comment by q4osteam** [comment]
We will check it and post back

**Comment by q4osteam** [comment]
Popup menu arrows look is dependent on the application style and it's not configurable for current TDE styles. Now it's only possible to change the default arrows style to "v-style" in qtcurve style configuration. We could make code changes to the qtcurve style to make the arrows customizable some way. Please let us know, if you would like us to make the changes for qtcurve or another style.

**Comment by seb3773** [comment]
I understand. I don't think this worth the trouble, this is just a small detail. (I wanted the arrows to be just like win10 menu ones, bottom oriented, but this is not very "logic" given the way the sub menus are displayed). Thanks for checking this :)
